### PR TITLE
Add rewritten code base

### PR DESCRIPTION
**Pull request by zimme**
So here's the rewrite.

I've worked a bit on it and thought we should discuss a bit before I actually publish this as 0.4.0? 2.0.0?

Have look and test it out and see what you think

### CODE REVIEW

**Comment by zimme** [comment]
I also would want to rename the repo `atom-composer` instead. I feel it's nicer, but it's just a personal preference.

**Comment by alairock** [comment]
Zimme, looks okay, but I think there is a merge conflict. Resolve and I'll take another look at it.

**Comment by ovr** [comment]
ping @zimme

**Comment by zimme** [comment]
Of course there's a merge conflict, the whole code base is re-written. We'll just overwrite the current code base with this one. I'll do a manual merge locally and push it. =)

I just wanted a second set of eyes on the code before pushing it

**Comment by alairock** [comment]
@zimme I say go for it :+1:

**Comment by zimme** [comment]
Merged, published version `v0.4.0`

**Comment by zimme** [comment]
Do you have access to a windows machine?

I hope the latest version will work with windows too.

**Comment by alairock** [comment]
I do not. :\ Windows is still a thing? :P

**Comment by zimme** [comment]
lol, yeah... guess the windows people will complain soon enough if it doesn't work =P

**Pull request closed without merging**
